### PR TITLE
show OS, container and version to test in TF

### PR DESCRIPTION
**Pull request by zmiklank**
Resolves: https://github.com/sclorg/container-common-scripts/issues/300

### CODE REVIEW

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
[test]

**Comment by zmiklank** [comment]
This seems to be working.
See name of the tests here: https://artifacts.dev.testing-farm.io/af2c116c-1c37-4bd0-8d26-77c936047cc1/.

I'll adjust also the rest of the plans.

**Review by phracek — APPROVED** [review]

**Pull request merged**
